version: '2'

services:
        barcode-1:
            extends:
                file: barcode_dc/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - bs1.docker.local
            logging:
                driver: syslog
                options:
                    tag: docker-barcode-1
            restart: unless-stopped
            environment:
                - USER_CONFIG_FILE=./config/config_1.toml
       
        barcode-2:
            extends:
                file: barcode_dc/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - bs2.docker.local
            logging:
                driver: syslog
                options:
                    tag: docker-barcode-2
            restart: unless-stopped
            environment:
                - USER_CONFIG_FILE=./config/config_2.toml

        barcode-3:
            extends:
                file: barcode_dc/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - bs3.docker.local
            logging:
                driver: syslog
                options:
                    tag: docker-barcode-3
            restart: unless-stopped
            environment:
                - USER_CONFIG_FILE=./config/config_3.toml

        barcode-4:
            extends:
                file: barcode_dc/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - bs4.docker.local
            logging:
                driver: syslog
                options:
                    tag: docker-barcode-4
            restart: unless-stopped
            environment:
                - USER_CONFIG_FILE=./config/config_4.toml

        dashboard-ui:
            extends:
                file: dashboard_ui/app.yml
                service: app
            networks:
                        internal:
                                aliases:
                                        - dashboard-ui.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-dashboard-ui
            restart: unless-stopped
            env_file:
                - django_secret_key
            depends_on:
              - "job-db"
 
        job-db:
            extends:
                file: locations_sds/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - job-db.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-job-db
            restart: unless-stopped
            env_file:
                - django_secret_key
 
        user-input:
            extends:
                file: user_input_dc/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - user-input.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-user-input
            restart: unless-stopped
            env_file:
                - django_secret_key
 
        mqtt-broker:
            extends:
                file: mqtt_broker/app.yml
                service: app
            networks:
                internal:
                    aliases:
                        - mqtt.docker.local
            logging:
                    driver: syslog
                    options:
                            tag: docker-mqtt
            restart: unless-stopped
        timeseries-db:
            extends:
                file: timeseries_sds/app.yml
                service: db
            networks:
                internal:
                    aliases:
                        - timeseries-db.docker.local
            logging:
                driver: syslog
                options:
                    tag: docker-timeseries-db
            restart: unless-stopped
            depends_on:
                - "mqtt_broker"
        timeseries-db-input:
            extends:
                file: timeseries_sds/app.yml
                service: telegraf
            networks:
                internal:
                    aliases:
                        - timeseries-input.docker.local
            logging:
                driver: syslog
                options:
                    tag: docker-timeseries-input
            restart: unless-stopped
            depends_on:
                - "timeseries-db"
                - "mqtt_broker"


networks:
        internal:
            name: shoestring-internal
