[input.scanner]
serial="0483_0011"
connection_point=["0","1.4"]
platform = "fd500000.pcie-pci-0000:01:00.0"

[[variable]]
    name="location"
    type="static"
    value="Station 1"

[[variable]]
    name="id"
    type="single"
    pattern='\s*(.*(?<=[\S]))\s*'
